apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsmysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsmysql-app
  template:
    metadata:
      labels:
        app: smsmysql-app
    spec:
      # initContainers:
      # - name: restore-data
      #   image: mysql:latest
      #   command: ["sh", "-c", "cp /app/backup.sql /docker-entrypoint-initdb.d/backup.sql"]
      #   volumeMounts:
      #     - name: app-hostpath
      #       mountPath: /app
      containers:
        - name: mysql-container
          image: mysql:8.0.33
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: kiran
            - name: MYSQL_DATABASE
              value: sms
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: smsmysql-persistent-storage
              mountPath: /var/lib/mysql 
            # - name: app-hostpath
            #   mountPath: /app
      volumes:
        - name: smsmysql-persistent-storage
          persistentVolumeClaim:
            claimName: smsmysql-pv-claim
        # - name: app-hostpath
        #   hostPath:
        #     path: /app 
---
apiVersion: v1
kind: Service
metadata:
  name: smsmysql-service
spec:
  selector:
    app: smsmysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None 
