apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsmysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsmysql-app
  template:
    metadata:
      labels:
        app: smsmysql-app
    spec:
      initContainers:
        - name: clear-data
          image: mysql:8.0.33
          command: ["sh", "-c", "rm -rf /var/lib/mysql/*"]
          volumeMounts:
            - name: smsmysql-persistent-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-container
          image: mysql:8.0.33
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: kiran
            - name: MYSQL_DATABASE
              value: sms
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: smsmysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: smsmysql-persistent-storage
          persistentVolumeClaim:
            claimName: smsmysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: smsmysql-service
spec:
  selector:
    app: smsmysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
