apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsapp-deployment
  template:
    metadata:
      labels:
        app: smsapp-deployment
    spec:
      containers:
        - name: smsapp-container
          image: kirangothe/springboot-mysql-sms:latest
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: sms-persistent-storage
              mountPath: /app
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://smsmysql-service:3306/sms?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: kiran
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: DEBUG
  volumes:
    - name: sms-persistent-storage
      persistentVolumeClaim:
        claimName: jar-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: smsmysql-service
spec:
  selector:
    app: smsapp-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30010
  type: NodePort
